baseurl = "http://docs.ssgaas.com"
title = "SSGAAS Documentation"
languageCode = "en-us"
theme="ssgaas"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Quickstart"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "quickstart"
    url = "/quickstart/"
  [[menu.main]]
    name = "How-To's"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "howtos"
    url = "/howtos/"
  [[menu.main]]
    name = "Reference"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "reference"
    url = "/reference/"
