# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "ssgaas"
license = "MIT"
licenselink = "https://github.com/ssgaas/faq/LICENSE.md"
description = "Hugo FAQ Theme for SSGAAS"
homepage = "http://ssgaas.com/"
tags = []
features = []
min_version = 0.15

[author]
  name = "Raul Perez"
  homepage = "http://repejota.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
